// Helps 分頁內容生成（純函式，由 tui.js 抽出）
const { T } = require('./theme')

    function buildHelps() {
        const tocs = []
        const lines = []
        const L = (s) => lines.push(s)
        const H = (label) => { tocs.push({ level: 0, label, lineNo: lines.length }); L(`  {${T.primary}-fg}{bold}▎${label}{/bold}{/}`) }
        const SH = (label) => { tocs.push({ level: 1, label, lineNo: lines.length }); L(`  {${T.secondary}-fg}{bold}${label}{/bold}{/}`) }
        const K  = (k) => `{${T.accent}-fg}${k}{/}`
        const C  = (c) => `{${T.warning}-fg}${c}{/}`
        const D  = (d) => `{${T.muted}-fg}${d}{/}`
        const row = (left, right) => `    ${left.padEnd(28)} ${right}`

        L('')
        L(`  {${T.primary}-fg}{bold}Helps — One-For-All 使用說明{/bold}{/}`)
        L(D('    本頁分成 [TUI 指令] 與 [Bot 指令] 兩部分。左側目錄 + Enter 跳節,滑鼠滾輪逐行捲動內容,Tab 切換目錄/內容焦點'))
        L('')

        // ════════════════════════════════════════════
        // PART 1 — TUI 指令
        // ════════════════════════════════════════════
        H('TUI 指令')

        SH('分頁與導航')
        L(row(K('← / →') + ' 或 ' + K('1–5'), '切換分頁 (Dashboard / Console / Profiles / Helps / Settings)'))
        L(row(K('/'), '進入指令模式 (聚焦下方 Command bar)'))
        L(row(K('Esc'), '取消指令 / 離開 wizard 步驟'))
        L(row(K('Enter'), '送出指令 / wizard 下一步'))
        L(row(K('↑ / ↓') + D(' (指令模式)'), '走 Command 歷史'))
        L(row(K('Ctrl-C'), '結束程式 (1=確認提示,2=graceful 關閉,3=SIGKILL;5s 內未確認自動取消)'))
        L('')

        SH('Console 分頁 — Bots 列表 (L / C / D / ▶◦)')
        L(row(K('l'), '切換選取 bot 的日誌過濾 (L 綠=顯示)'))
        L(row(K('d'), '切換選取 bot 的 DEBUG 訊息顯示 (D 綠=顯示)'))
        L(D('    C 標誌來自 profiles.json 的 chat 設定 (read-only)'))
        L(D('    ▶ 表示 childProcess 在執行,◦ 表示已停止'))
        L('')

        SH('Console 分頁 — Logs 區')
        L(row(K('m'), '切換 mouse / copy 模式 (copy 模式可框選複製文字)'))
        L(row(K('滾輪 / ↑↓ k j PgUp PgDn'), '捲動日誌'))
        L(row(K('G'), '跳到底部 (恢復 follow)'))
        L(row(K('g'), '跳到頂部 (停止 follow,標籤顯示新訊息計數)'))
        L('')

        SH('Console 分頁 — Infos / Detail')
        L(D('    Infos: 名稱 / 座標 / Server / Ping / Balance / Coin / 任務佇列'))
        L(D('    Detail: 當前任務的子模組進度 (autoquest / build / cleararea / villager / wms)'))
        L(D('    每 3 秒向 child 拉取一次資料 + 收到 push 即更新'))
        L(D('    bot 未執行時,Infos / Detail 不會顯示舊資料 (Dashboard 也是)'))
        L('')

        SH('Profiles 分頁 — Profiles 子頁 (預設)')
        L(row(K('Tab'), '切換到 Connection 子頁'))
        L(row(K('a'), '新增 profile (7 步驟 wizard,寫入 profiles.json)'))
        L(row(K('e'), '編輯選取 profile (6 步驟,跳過 Name)'))
        L(row(K('d'), '刪除選取 profile (y/n 確認)'))
        L(row(K('J / K'), '往下 / 往上移動,順序寫入 profiles.json'))
        L(row(K('s'), '切換選取 profile 的 auto-start (寫入 config.toml 的 ' + C('account.id') + ')'))
        L(D('    ★ = 在 auto-start 列表中 (下次開啟會載入)'))
        L(D('    任何 wizard 步驟按 Esc 都會取消整個流程'))
        L('')

        SH('Profiles 分頁 — Connection 子頁 (Tab 進入)')
        L(row(K('Tab'), '切換回 Profiles 子頁'))
        L(row(K('↑ / ↓'), '在區段間移動 (跳過 header)'))
        L(row(K('PgUp / PgDn'), '快速翻頁'))
        L(row(K('Home / End'), '跳到第一 / 最後一個可選列'))
        L(row(K('e') + ' or ' + K('Enter'), '對 text/數值欄位開始 inline 編輯'))
        L(row(K('s') + ' or ' + K('Space'), '切換 toggle (selectBestIP)'))
        L(row(K('Enter') + D(' (action)'), '觸發動作 (例:重新偵測最佳 IP)'))
        L(row(K('a'), '在當前列表加入新項目 (進入 inline 輸入)'))
        L(row(K('d'), '刪除當前 list-item'))
        L(row(K('J / K'), 'IP 清單往下 / 往上移序'))
        L(D('    inline 編輯時 Enter=送出,Esc=取消;所有寫入會 surgical 改 config.toml'))
        L(D('    可調項目:selectBestIP / reconnect_CD / CheckPing / pingThreshold / setting.ips'))
        L('')

        SH('Settings 分頁 — Discord / 全域日誌 / MC 白名單')
        L(row(K('↑ / ↓'), '在區段間移動 (跳過 header)'))
        L(row(K('PgUp / PgDn'), '快速翻頁'))
        L(row(K('Home / End'), '跳到第一 / 最後一個可選列'))
        L(row(K('e') + ' or ' + K('Enter'), '對 text 欄位開始 inline 編輯 (含 token)'))
        L(row(K('s') + ' or ' + K('Space'), '切換 toggle'))
        L(row(K('Enter') + D(' (action)'), '觸發動作 (套用啟用 / 測試 token / 發送測試訊息)'))
        L(row(K('a / d'), '對白名單列表加入 / 刪除項目'))
        L(D('    Token 顯示為遮罩,只有最後 4 碼可見;編輯時看完整 buffer'))
        L(D('    全域 DEBUG/CHAT 切換為 in-memory,不寫入 config'))
        L(D('    Discord 變更寫入 config.toml,「套用」可立即啟動/停止 client'))
        L(D('    操作成功 / 失敗會在最下方狀態列以彩色訊息提示數秒'))
        L('')

        SH('Helps 分頁 — 本頁')
        L(row(K('Tab'), '切換焦點 內容 ⇄ 目錄'))
        L(row(K('滑鼠滾輪') + D(' (內容焦點)'), '逐行捲動右側內容 (1 行/格);左側目錄跟著 highlight'))
        L(row(K('滑鼠滾輪') + D(' (目錄焦點)'), '移動目錄選擇 ±1,內容立即跳到該節開頭'))
        L(row(K('Enter') + D(' (目錄焦點)'), '把內容跳到目前選中的目錄項'))
        L(D('    本頁不再使用方向鍵 — 全部以滾輪 + Tab + Enter 操作'))
        L('')

        SH('Command Bar — 頂層指令 (前綴 .)')
        L(D('    指令模式下輸入。沒有 . 前綴 = 透過目前選取 bot 發 MC 聊天'))
        L(row(C('.list'), '列出所有 bot (Id / Name / Status / Type / CrtType)'))
        L(row(C('.switch <name|id>'), '切換目前操作的 bot'))
        L(row(C('.create [name]'), '啟動 profile (省略名稱=啟動目前選取的)'))
        L(row(C('.c [name]'), '同 ' + C('.create')))
        L(row(C('.reload'), '重新載入目前 bot (在原 reloadCD 之後重啟)'))
        L(row(C('.exit'), '結束目前 bot 的 child / 取消其重啟計時'))
        L(row(C('.all <text>'), '把 ' + D('<text>') + ' 送到所有正在執行的 bot'))
        L(row(C('.task list'), '列出當前 bot 任務佇列 (線上 / 離線通用)'))
        L(row(C('.task remove all'), '清空當前 bot 全部佇列任務'))
        L(row(C('.task remove top'), '移除佇列最前面那筆 (執行中只清持久化,不中斷)'))
        L(row(C('.task remove <N>'), '移除 1-indexed 第 N 筆任務'))
        L(row(C('.ff'), 'force exit 整個程式 (' + D('process.exit(0)') + ')'))
        L(row(C('.clear'), '清除 log 面板所有訊息'))
        L(row(C('.test <args>'), '回顯 args 到 log,作測試用'))
        L(row(C('/exit') + ' or ' + C('/quit'), '結束 TUI 與所有 bot (TUI 專用)'))
        L(D('    ' + C('.task') + ' 對「離線 bot」會直接讀寫 ' + C('config/<bot>/task.json') + ',下次啟動生效'))
        L('')

        // ════════════════════════════════════════════
        // PART 2 — Bot 指令
        // ════════════════════════════════════════════
        H('Bot 指令')
        L(D('    透過目前選取 bot 執行子模組指令。三種來源:'))
        L(D('      Console:加 ' + C('.') + ' 前綴送出,例 ' + C('.help') + '、' + C('.bt build')))
        L(D('      遊戲內 DM:' + C('/m <bot> <cmd>') + ' 不加 . (發送者需在 ' + C('config.setting.whitelist') + ' 內)'))
        L(D('      Discord:啟用 ' + C('discord_setting.activate') + ' 後可透過 channel 控制 (見 config.toml)'))
        L('')

        SH('basicCommand — 通用')
        L(row(C('help / ? / usage'), '列出所有已註冊指令樹'))
        L(row(C('info / i / stats'), '完整 bot 資訊 (座標 / 經驗 / 物品欄)'))
        L(row(C('balance / bal / money'), '查綠 / 村莊幣餘額'))
        L(row(C('xp / exp / experience'), '查經驗等級 / 點數 / 進度'))
        L(row(C('plist'), '透過 /tpa 補完取得線上玩家清單'))
        L(row(C('find <name...>'), '查詢玩家所在分流'))
        L(row(C('vtrank / emrank'), '統計綠寶石合成次數 (raid 排行)'))
        L(row(C('warp <name>'), '/warp 至指定點'))
        L(row(C('ts / server <n>'), '傳送至分流 ' + D('<n>')))
        L(row(C('tpc <owner> [idx]'), '傳送至玩家領地 (預設 idx=1)'))
        L(row(C('goto <x> <y> <z>'), 'pathfinder fly 到座標'))
        L(row(C('throw <slot...>'), '丟棄指定欄位'))
        L(row(C('throwall'), '丟棄背包所有欄位 (slot 9–45)'))
        L(row(C('qt'), '丟垃圾 (保留 netherite 工具 + 釣竿)'))
        L(row(C('say <text>'), '透過 bot 發 MC 聊天訊息'))
        L(row(C('payall / withdraw'), '把全部綠 pay 給發起者 (僅 ' + C('/m') + ')'))
        L(row(C('地鳴宣言 [ch|jp]'), '發送地鳴宣言 (預設 ch)'))
        L(row(C('exit'), '結束此 bot'))
        L(row(C('tl'), '印出 taskManager 內任務佇列 (raw)'))
        L(row(C('task list'), '美化版任務佇列 (▶ 標記執行中)'))
        L(row(C('task remove <all|top|N>'), '移除佇列任務 (' + C('.task') + ' 為等價的離線可用版本)'))
        L(row(C('click <slot>') + ' / ' + C('interact <x y z>'), '低階測試 (window click / 方塊互動)'))
        L('')

        SH('mp — 地圖畫 (mapart)')
        L(row(C('mp set <file> <x> <y> <z>'), '設定 schematic 與放置點'))
        L(row(C('mp info / i'), '查詢目前設定'))
        L(row(C('mp material / m'), '在材料站生成所需材料'))
        L(row(C('mp file / f'), '匯出材料清單為檔案'))
        L(row(C('mp build / b'), '開始建造'))
        L(row(C('mp pause / p'), '暫停建造'))
        L(row(C('mp resume / r'), '繼續建造'))
        L(row(C('mp stop / s'), '中止建造'))
        L(row(C('mp open / o'), '開圖 (放置完成後將圖載入)'))
        L(row(C('mp name / n'), '為地圖命名'))
        L(row(C('mp copy / c'), '複印地圖'))
        L(row(C('mp wrap / w'), '分裝 (整理至潛影盒)'))
        L('')

        SH('bt / lp / farm / buildtool — 投影建造 / 自動化建材')
        L(row(C('bt set <file> <x> <y> <z>'), '設定 schematic 與放置點'))
        L(row(C('bt info / i'), '查詢設定'))
        L(row(C('bt build / b'), '開始建造'))
        L(row(C('bt pause / p'), '暫停建造'))
        L(row(C('bt resume / r'), '繼續建造'))
        L(row(C('bt stop / s'), '中止建造'))
        L(row(C('bt iron'), '鐵礦自動化'))
        L(row(C('bt portal'), '傳送門'))
        L(row(C('bt farm'), '瓜機種田'))
        L(row(C('bt f4'), '四作物種田'))
        L(row(C('bt prepare'), '種田前置'))
        L(row(C('bt debug'), '印出當前背包統計'))
        L('')

        SH('ca / cleararea — TNT 區域清理')
        L(row(C('ca set'), '設定清理範圍 (依 mpStation 設定)'))
        L(row(C('ca expand'), '擴張範圍'))
        L(row(C('ca shift'), '平移範圍'))
        L(row(C('ca info / i'), '查詢設定'))
        L(row(C('ca tnt'), '以 TNT 模式清理'))
        L(row(C('ca execute / e'), '執行清理 (一般模式)'))
        L(row(C('ca pause / p'), '暫停'))
        L(row(C('ca resume / r'), '繼續'))
        L(row(C('ca stop / s / c'), '中止'))
        L('')

        SH('aq / quest — 自動任務 (AutoQuest)')
        L(row(C('aq start / run'), '開始跑任務'))
        L(row(C('aq stop / s'), '停止'))
        L(row(C('aq info / i'), '基本資訊'))
        L(row(C('aq show'), '顯示任務狀態'))
        L(row(C('aq detail'), '展開細節 (進度 / 獎勵 / 期限)'))
        L(row(C('aq debug / d'), 'debug'))
        L(D('    全域設定: ' + C('config/global/autoQuest.toml')))
        L('')

        SH('wms — Warehouse Management')
        L(row(C('wms run / r'), '進入 daemon 模式 (自動拉取訂單執行)'))
        L(row(C('wms stop / s'), '停止 daemon'))
        L(row(C('wms update / u'), '更新桶子標記'))
        L(row(C('wms query / q <item>'), '查詢庫存'))
        L(row(C('wms withdraw / w <item> <qty>'), '出貨'))
        L(row(C('wms deposit / d'), '入庫 (背包入倉)'))
        L(row(C('wms dp'), '入庫到揀貨區'))
        L(row(C('wms order / o <id>'), '手動執行單一訂單'))
        L(row(C('wms sort'), '整理拒收區'))
        L(row(C('wms test / t'), '測試流程'))
        L(D('    參考: ' + C('wmsapi.md') + ' / ' + C('lib/wms/*')))
        L('')

        SH('vt / villager / v — 村民交易')
        L(row(C('vt iron'), '鐵村民交易'))
        L(row(C('vt mp / melonpumpkin'), '雙瓜交易'))
        L(row(C('vt train'), '訓練村民'))
        L(row(C('vt cr / curerename'), '治療 + 改名'))
        L(row(C('vt put'), '放置村民'))
        L(row(C('vt eff / efficiency'), '查看目前交易效率(綠寶石/分·時)'))
        L(row(C('vt stop'), '停止當前流程'))
        L('')

        // ── 設定檔 ──
        H('重要設定檔')
        L(row(C('config.toml'), 'IP 選擇 / 重啟 CD / Discord / 啟動清單 (account.id)'))
        L(row(C('profiles.json'), 'Bot 帳號 (name / type / username / host / port / debug / chat)'))
        L(row(C('config/<bot>/*'), '個別 bot 的模組設定 (lp.json, villager.toml...)'))
        L(row(C('config/global/*.json'), '所有 bot 共用設定 (lp.json, autoQuest.toml...)'))
        L(row(C('logs/*.log'), '日誌輸出'))
        L('')

        H('小提醒')
        L(D('  ・指令模式下輸入無 . 前綴的文字 = 透過目前 bot 發 MC 聊天訊息'))
        L(D('  ・enableEXPTUI=false 時退回到傳統 readline (無此 TUI 介面)'))
        L(D('  ・selectBestIP=true 會自動 ping config.setting.ips 內的 IP 選最佳'))
        L(D('  ・bot 執行子模組任務時可在 Console 分頁的 Detail 看到即時進度'))
        L('')
        return { lines, tocs }
    }
    function helpsTocItem(t) {
        return t.level === 0
            ? ` {${T.primary}-fg}{bold}${t.label}{/bold}{/}`
            : `   {${T.subtext}-fg}${t.label}{/}`
    }

module.exports = { buildHelps, helpsTocItem }
